### ISSUE TITLE
使用 Docker Compose 部署后端失败

### ISSUE THREAD

**Issue by lei2rock** [lizheming/waline#48]
Docker Compose 文件如下：
```
services:
    wlaine:
        image: lizheming/waline
        container_name: waline
        restart: always
        ports:
            - '8360:8360'
        environment:
            LEAN_ID: 'xxx'
            LEAN_KEY: 'xxx'
            LEAN_MASTER_KEY: 'xxx'
```

Leancloud 是国际版，使用 `docker-compose up -d` 命令启动，设置好了反代到 http://waline.dlzhang.com ， 但是似乎不能注册用户（提示404） http://waline.dlzhang.com/ui/register
